### ISSUE TITLE
Defaut VS map icon displayed

### ISSUE THREAD

**Issue by OkinaNutoria** [snakeriot/vs-more-map-icons#1]
Hello,
I play VS in a dedicated sever with some friends. We tried to use your mode (More Map Icon) but we have en issue.
When we use the customs markers, it display the default marker to the map. But, if we trie to modify the map marker, it display that the marker selected is the custom.

Thanks in advance :)

![image](https://user-images.githubusercontent.com/121445857/209562022-4eff7c7e-ecf1-48c8-9c4c-78fcd1a826c1.png)
![image](https://user-images.githubusercontent.com/121445857/209562100-72661147-6594-4c86-b560-f1c5f748d1b1.png)

**Comment by snakeriot** [comment]
Hi! 
Thank you for the report, unfortunately it's known issue, I've posted solution for it on the mod's page under "To make this mod work you need:" section.
I've tried to resolve it on my end, but it appears to be the problem with game's source code, I've submitted PR into VS repository to resolve it, but Tyron answered that in next major release they will completely rework this code (https://www.vintagestory.at/forums/topic/10416-more-map-icons-addition-thru-mods/)!

So for now I would suggest to use workaround from mod's page

**Comment by OkinaNutoria** [comment]
Oh OK, thank to answering me. It's my friend who pay the server and
download the mod, I haven't see the mod DB page.
Have a great day.

Le lun. 26 déc. 2022 à 16:54, Denis Novik ***@***.***> a
écrit :

**Comment by snakeriot** [comment]
Closing this task as resolved after game update to 1.18.8, since icons system was reworked in game, and now doesn't require code
