### ISSUE TITLE
Cannot get the icons to work.

### ISSUE THREAD

**Issue by CipherArrow** [snakeriot/vs-more-map-icons#2]
1.18.10 didn't work nor did 1.18.12 for me. It not only displays the entire default icons, in the actual waypoint chooser, but I even tried doing the minimap off trick on loading the game and still does not work. Why isn't it working? It's simple enough so it should, shouldn't it?

**Comment by snakeriot** [comment]
@Diometus , wow, I've testied on 1.18.10 and works like a charm for me (screenshot attached)
![image](https://github.com/snakeriot/vs-more-map-icons/assets/7020584/6fd705ab-9c35-431c-9ba9-8fab6ef68819)

One of the suggestions that I have - is that you have some mod that overwrites icons layout generation (for some reason)

**Comment by snakeriot** [comment]
If that's not a lot of trouble, I would ask you to disable all the mods except this one, and try on empty "test" world

**Comment by CipherArrow** [comment]
Okay I'll try an empty test and slowly enable 1 by 1 and see which one it is that is causing the issue. Once I find out which one it is, I'll report it here to you so please keep this open.

**Comment by CipherArrow** [comment]
I tried all the mods I had but the following mods in singleplayer since they are server only side:
Th3Essentials 

It doesn't do it when I play singleplayer, only when I  play Multiplayer. Also, not only did I try my own server but also Rogue House with all client mods disabled but your More maps icons.

I then went and found a server online with zero mods installed and left only More maps icons mod installed and it doesn't work there either (server name was Village Life PvE).

**Comment by CipherArrow** [comment]
I found out what it was!

the mod file: modinfo.json

did not have "side": "client",     in it thus is why it would work only in singleplayer but never in multiplayer for me. By adding that line, it now works for me!

**Comment by snakeriot** [comment]
Aha, it was intentional decision - to make it "both" sides mod (it's listed like that in mod db).

The reason for that - I wanted to include it as "required" into servers where it is installed.

But now I see that it was pretty bad decision :D today will post new version of the mod with "side": "client" and close this issue accordingly

**Comment by snakeriot** [comment]
Closing this issue as done, mod side changed to Client
